apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: site2-resync-triggertemplate
spec:
  params:
    - name: p
      type: string 
      default: "rbd"
    - name: i1
      type: string
      default: "rbd/mysql-pv-claim-wordpress-tektonfa0c9c9a-bb35-11ea-beb2-0a580a830019"
    - name: i2
      type: string
      default: "rbd/wp-pv-claim-wordpress-tektonfa0a6dfa-bb35-11ea-beb2-0a580a830019"
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: multisite-$(uid)
      spec:
        type: git
        params:
        - name: p
          value: "rbd"
        - name: i1
          value: "rbd/mysql-pv-claim-wordpress-tektonfa0c9c9a-bb35-11ea-beb2-0a580a830019"
        - name: i2
          value: "rbd/wp-pv-claim-wordpress-tektonfa0a6dfa-bb35-11ea-beb2-0a580a830019"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: site2-resync-$(uid)
        generateName: site2-resync-
      spec:
        pipelineRef:
          name: rbd-resync-images
        params:
          - name: pathToYamlFile
            value: "tekton/wordpress/overlays/site2"
        serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: site2-resync-pipelinebinding
spec:
  params:
    - name: p
      value: "rbd"
    - name: i1
      value: "rbd/mysql-pv-claim-wordpress-tektonfa0c9c9a-bb35-11ea-beb2-0a580a830019"
    - name: i2
      value: "rbd/wp-pv-claim-wordpress-tektonfa0a6dfa-bb35-11ea-beb2-0a580a830019"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: resync-webhook
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: site2-resync-pipelinebinding
    template:
      name: site2-resync-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: resync-webhook
  name: site2-resync
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: el-resync-webhook
    weight: 100
