apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: rbd-resync-images
spec:
  params:
    - name: p
      type: string 
      default: "rbd"
    - name: i1
      type: string
      default: "rbd/mysql-pv-claim-wordpress-tektonfa0c9c9a-bb35-11ea-beb2-0a580a830019"
    - name: i2
      type: string
      default: "rbd/wp-pv-claim-wordpress-tektonfa0a6dfa-bb35-11ea-beb2-0a580a830019"
  tasks:
    - name: command-resync-images
      retries: 1
      taskRef:
        name: create-configmap-command
      params:
        - name: pool
          value: "$(params.p)"
        - name: action
          value: "resync"
        - name: image1
          value: "$(params.i1)"
        - name: image2
          value: "$(params.i2)"

    - name: execute-resync-command
      retries: 3
      taskRef:
        name: execute-rbd-configmap-command
      runAfter:
        - command-resync-images

    - name: delete-resync-configmap
      taskRef:
        name: delete-configmap
      runAfter:
        - execute-resync-command
